In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
art_facilities_index = pd.read_csv('drive/MyDrive/ArtIndex/seoul_facilities_data.csv')
art_facilities_index

,구,cul_fac_num_2021,cul_fac_num_2022,mil_fac_num_2021,mil_fac_num_2022,hall_num_2021,hall_num_2022,hall_rate_2021,hall_rate_2020,hall_people_2021,hall_people_2020,art_people_2021,art_people_2020
0,강남구,115,115,493.7,486.6,34,34,51.8,35.6,164,156,70,65
1,강동구,17,17,85.0,83.8,21,21,51.8,35.6,164,156,70,65
2,강북구,17,17,117.6,117.6,6,6,51.8,35.6,164,156,70,65
3,강서구,20,20,74.5,72.9,5,6,51.8,35.6,164,156,70,65
4,관악구,17,17,62.0,59.3,3,3,51.8,35.6,164,156,70,65
5,광진구,24,24,143.8,141.2,14,16,51.8,35.6,164,156,70,65
6,구로구,22,22,122.1,119.2,20,20,51.8,35.6,164,156,70,65
7,금천구,12,12,104.4,99.6,7,7,51.8,35.6,164,156,70,65
8,노원구,20,20,92.1,91.7,6,6,51.8,35.6,164,156,70,65
9,도봉구,23,23,166.4,166.3,5,5,51.8,35.6,164,156,70,65
10,동대문구,11,11,66.2,64.2,10,10,51.8,35.6,164,156,70,65
11,동작구,16,16,87.0,85.6,103,104,51.8,35.6,164,156,70,65
12,마포구,48,48,269.3,265.1,39,40,51.8,35.6,164,156,70,65
13,서대문구,26,26,181.7,176.6,9,9,51.8,35.6,164,156,70,65
14,서초구,43,43,250.4,255.4,38,39,51.8,35.6,164,156,70,65
15,성동구,16,16,118.8,119.8,11,11,51.8,35.6,164,156,70,65
16,성북구,25,25,128.7,126.3,14,14,51.8,35.6,164,156,70,65
17,송파구,25,25,89.1,87.5,13,13,51.8,35.6,164,156,70,65
18,양천구,16,16,88.4,88.3,6,6,51.8,35.6,164,156,70,65
19,영등포구,27,27,146.1,141.8,18,18,51.8,35.6,164,156,70,65
20,용산구,24,24,213.8,218.7,19,20,51.8,35.6,164,156,70,65
21,은평구,11,11,51.6,51.4,1,1,51.8,35.6,164,156,70,65
22,종로구,380,383,5155.2,5276.6,159,160,51.8,35.6,164,156,70,65
23,중구,56,56,891.1,871.5,267,268,51.8,35.6,164,156,70,65
24,중랑구,11,11,59.5,58.5,9,9,51.8,35.6,164,156,70,65

In [4]:
data = {
    '구': ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구'],
}

final_art_facilities_index = pd.DataFrame(data)
final_art_facilities_index

       구
0    강남구
1    강동구
2    강북구
3    강서구
4    관악구
5    광진구
6    구로구
7    금천구
8    노원구
9    도봉구
10  동대문구
11   동작구
12   마포구
13  서대문구
14   서초구
15   성동구
16   성북구
17   송파구
18   양천구
19  영등포구
20   용산구
21   은평구
22   종로구
23    중구
24   중랑구

In [5]:
data = {
    '구': ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구'],
}

cal_df = pd.DataFrame(data)
cal_df

       구
0    강남구
1    강동구
2    강북구
3    강서구
4    관악구
5    광진구
6    구로구
7    금천구
8    노원구
9    도봉구
10  동대문구
11   동작구
12   마포구
13  서대문구
14   서초구
15   성동구
16   성북구
17   송파구
18   양천구
19  영등포구
20   용산구
21   은평구
22   종로구
23    중구
24   중랑구

In [6]:
# 시설지수 계산
cal_df['cul_fac_num'] = art_facilities_index['cul_fac_num_2022']/art_facilities_index['cul_fac_num_2021']
cal_df['cul_fac_num'] = cal_df['cul_fac_num']*100
cal_df['mil_fac_num'] = art_facilities_index['mil_fac_num_2022']/art_facilities_index['mil_fac_num_2021']
cal_df['mil_fac_num'] = cal_df['mil_fac_num']*100
cal_df['hall_num'] = art_facilities_index['hall_num_2022']/art_facilities_index['hall_num_2021']
cal_df['hall_num'] = cal_df['hall_num']*100
cal_df['hall_rate'] = art_facilities_index['hall_rate_2020']/art_facilities_index['hall_rate_2021']
cal_df['hall_rate'] = cal_df['hall_rate']*100
cal_df['hall_num_rate'] = (cal_df['hall_num'] + cal_df['hall_rate'])/2
cal_df

       구  cul_fac_num  mil_fac_num    hall_num  hall_rate  hall_num_rate
0    강남구   100.000000    98.561880  100.000000  68.725869      84.362934
1    강동구   100.000000    98.588235  100.000000  68.725869      84.362934
2    강북구   100.000000   100.000000  100.000000  68.725869      84.362934
3    강서구   100.000000    97.852349  120.000000  68.725869      94.362934
4    관악구   100.000000    95.645161  100.000000  68.725869      84.362934
5    광진구   100.000000    98.191933  114.285714  68.725869      91.505792
6    구로구   100.000000    97.624898  100.000000  68.725869      84.362934
7    금천구   100.000000    95.402299  100.000000  68.725869      84.362934
8    노원구   100.000000    99.565689  100.000000  68.725869      84.362934
9    도봉구   100.000000    99.939904  100.000000  68.725869      84.362934
10  동대문구   100.000000    96.978852  100.000000  68.725869      84.362934
11   동작구   100.000000    98.390805  100.970874  68.725869      84.848371
12   마포구   100.000000    98.440401  102.564103  68.725869      85.644986
13  서대문구   100.000000    97.193176  100.000000  68.725869      84.362934
14   서초구   100.000000   101.996805  102.631579  68.725869      85.678724
15   성동구   100.000000   100.841751  100.000000  68.725869      84.362934
16   성북구   100.000000    98.135198  100.000000  68.725869      84.362934
17   송파구   100.000000    98.204265  100.000000  68.725869      84.362934
18   양천구   100.000000    99.886878  100.000000  68.725869      84.362934
19  영등포구   100.000000    97.056810  100.000000  68.725869      84.362934
20   용산구   100.000000   102.291862  105.263158  68.725869      86.994513
21   은평구   100.000000    99.612403  100.000000  68.725869      84.362934
22   종로구   100.789474   102.354904  100.628931  68.725869      84.677400
23    중구   100.000000    97.800471  100.374532  68.725869      84.550200
24   중랑구   100.000000    98.319328  100.000000  68.725869      84.362934

In [7]:
final_art_facilities_index['facilities_index'] = (cal_df['cul_fac_num'] + cal_df['mil_fac_num']+ cal_df['hall_num_rate'])/3
final_art_facilities_index

       구  facilities_index
0    강남구         94.308271
1    강동구         94.317057
2    강북구         94.787645
3    강서구         97.405094
4    관악구         93.336032
5    광진구         96.565908
6    구로구         93.995944
7    금천구         93.255078
8    노원구         94.642875
9    도봉구         94.767613
10  동대문구         93.780595
11   동작구         94.413059
12   마포구         94.695129
13  서대문구         93.852037
14   서초구         95.891843
15   성동구         95.068228
16   성북구         94.166044
17   송파구         94.189066
18   양천구         94.749937
19  영등포구         93.806582
20   용산구         96.428792
21   은평구         94.658446
22   종로구         95.940592
23    중구         94.116891
24   중랑구         94.227421

In [8]:
# 시설인력지수 계산
cal_df['hall_people'] = art_facilities_index['hall_people_2020']/art_facilities_index['hall_people_2021']
cal_df['hall_people'] = cal_df['hall_people']*100
cal_df['art_people'] = art_facilities_index['art_people_2020']/art_facilities_index['art_people_2021']
cal_df['art_people'] = cal_df['art_people']*100

cal_df

,구,cul_fac_num,mil_fac_num,hall_num,hall_rate,hall_num_rate,hall_people,art_people
0,강남구,100.000000,98.561880,100.000000,68.725869,84.362934,95.121951,92.857143
1,강동구,100.000000,98.588235,100.000000,68.725869,84.362934,95.121951,92.857143
2,강북구,100.000000,100.000000,100.000000,68.725869,84.362934,95.121951,92.857143
3,강서구,100.000000,97.852349,120.000000,68.725869,94.362934,95.121951,92.857143
4,관악구,100.000000,95.645161,100.000000,68.725869,84.362934,95.121951,92.857143
5,광진구,100.000000,98.191933,114.285714,68.725869,91.505792,95.121951,92.857143
6,구로구,100.000000,97.624898,100.000000,68.725869,84.362934,95.121951,92.857143
7,금천구,100.000000,95.402299,100.000000,68.725869,84.362934,95.121951,92.857143
8,노원구,100.000000,99.565689,100.000000,68.725869,84.362934,95.121951,92.857143
9,도봉구,100.000000,99.939904,100.000000,68.725869,84.362934,95.121951,92.857143
10,동대문구,100.000000,96.978852,100.000000,68.725869,84.362934,95.121951,92.857143
11,동작구,100.000000,98.390805,100.970874,68.725869,84.848371,95.121951,92.857143
12,마포구,100.000000,98.440401,102.564103,68.725869,85.644986,95.121951,92.857143
13,서대문구,100.000000,97.193176,100.000000,68.725869,84.362934,95.121951,92.857143
14,서초구,100.000000,101.996805,102.631579,68.725869,85.678724,95.121951,92.857143
15,성동구,100.000000,100.841751,100.000000,68.725869,84.362934,95.121951,92.857143
16,성북구,100.000000,98.135198,100.000000,68.725869,84.362934,95.121951,92.857143
17,송파구,100.000000,98.204265,100.000000,68.725869,84.362934,95.121951,92.857143
18,양천구,100.000000,99.886878,100.000000,68.725869,84.362934,95.121951,92.857143
19,영등포구,100.000000,97.056810,100.000000,68.725869,84.362934,95.121951,92.857143
20,용산구,100.000000,102.291862,105.263158,68.725869,86.994513,95.121951,92.857143
21,은평구,100.000000,99.612403,100.000000,68.725869,84.362934,95.121951,92.857143
22,종로구,100.789474,102.354904,100.628931,68.725869,84.677400,95.121951,92.857143
23,중구,100.000000,97.800471,100.374532,68.725869,84.550200,95.121951,92.857143
24,중랑구,100.000000,98.319328,100.000000,68.725869,84.362934,95.121951,92.857143

In [9]:
final_art_facilities_index['facilities_people_index'] = (cal_df['hall_people'] + cal_df['art_people'])/2
final_art_facilities_index

       구  facilities_index  facilities_people_index
0    강남구         94.308271                93.989547
1    강동구         94.317057                93.989547
2    강북구         94.787645                93.989547
3    강서구         97.405094                93.989547
4    관악구         93.336032                93.989547
5    광진구         96.565908                93.989547
6    구로구         93.995944                93.989547
7    금천구         93.255078                93.989547
8    노원구         94.642875                93.989547
9    도봉구         94.767613                93.989547
10  동대문구         93.780595                93.989547
11   동작구         94.413059                93.989547
12   마포구         94.695129                93.989547
13  서대문구         93.852037                93.989547
14   서초구         95.891843                93.989547
15   성동구         95.068228                93.989547
16   성북구         94.166044                93.989547
17   송파구         94.189066                93.989547
18   양천구         94.749937                93.989547
19  영등포구         93.806582                93.989547
20   용산구         96.428792                93.989547
21   은평구         94.658446                93.989547
22   종로구         95.940592                93.989547
23    중구         94.116891                93.989547
24   중랑구         94.227421                93.989547

In [10]:
# 예술시설지수
final_art_facilities_index['art_facilities_index'] = final_art_facilities_index['facilities_index'] + final_art_facilities_index['facilities_people_index']
final_art_facilities_index['art_facilities_index'] = final_art_facilities_index['art_facilities_index']/2
final_art_facilities_index

       구  facilities_index  facilities_people_index  art_facilities_index
0    강남구         94.308271                93.989547             94.148909
1    강동구         94.317057                93.989547             94.153302
2    강북구         94.787645                93.989547             94.388596
3    강서구         97.405094                93.989547             95.697321
4    관악구         93.336032                93.989547             93.662789
5    광진구         96.565908                93.989547             95.277728
6    구로구         93.995944                93.989547             93.992746
7    금천구         93.255078                93.989547             93.622312
8    노원구         94.642875                93.989547             94.316211
9    도봉구         94.767613                93.989547             94.378580
10  동대문구         93.780595                93.989547             93.885071
11   동작구         94.413059                93.989547             94.201303
12   마포구         94.695129                93.989547             94.342338
13  서대문구         93.852037                93.989547             93.920792
14   서초구         95.891843                93.989547             94.940695
15   성동구         95.068228                93.989547             94.528888
16   성북구         94.166044                93.989547             94.077796
17   송파구         94.189066                93.989547             94.089307
18   양천구         94.749937                93.989547             94.369742
19  영등포구         93.806582                93.989547             93.898064
20   용산구         96.428792                93.989547             95.209169
21   은평구         94.658446                93.989547             94.323996
22   종로구         95.940592                93.989547             94.965070
23    중구         94.116891                93.989547             94.053219
24   중랑구         94.227421                93.989547             94.108484

In [11]:
final_art_facilities_index.to_csv('drive/MyDrive/ArtIndex/final_art_facilities_index.csv', encoding='utf-8-sig', index=False)