# artistic_creation_production_index

In [1]:
import pandas as pd
import numpy as np

In [5]:
# 최종 지표 값들을 정리할 table
# 서울시 구별 데이터
data = {
    '구': ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구'],
}
# 데이터 프레임 생성
final_art_manpower_index = pd.DataFrame(data)
final_art_manpower_index

       구
0    강남구
1    강동구
2    강북구
3    강서구
4    관악구
5    광진구
6    구로구
7    금천구
8    노원구
9    도봉구
10  동대문구
11   동작구
12   마포구
13  서대문구
14   서초구
15   성동구
16   성북구
17   송파구
18   양천구
19  영등포구
20   용산구
21   은평구
22   종로구
23    중구
24   중랑구

In [6]:
art_manpower_index = pd.read_csv('../Seoul_data/art_manpower_index.csv')
art_manpower_index

,구,ContentsCreator_2021,ContentsCreator_2022,performanceTeam_2020,performanceTeam_2021,applicants_2022,applicants_2023,Content_2019,Content_2020
0,강남구,463268,619953,1854,1826,2872,3402,126978,62139
1,강동구,463268,619953,1854,1826,2872,3402,126978,62139
2,강북구,463268,619953,1854,1826,2872,3402,126978,62139
3,강서구,463268,619953,1854,1826,2872,3402,126978,62139
4,관악구,463268,619953,1854,1826,2872,3402,126978,62139
5,광진구,463268,619953,1854,1826,2872,3402,126978,62139
6,구로구,463268,619953,1854,1826,2872,3402,126978,62139
7,금천구,463268,619953,1854,1826,2872,3402,126978,62139
8,노원구,463268,619953,1854,1826,2872,3402,126978,62139
9,도봉구,463268,619953,1854,1826,2872,3402,126978,62139
10,동대문구,463268,619953,1854,1826,2872,3402,126978,62139
11,동작구,463268,619953,1854,1826,2872,3402,126978,62139
12,마포구,463268,619953,1854,1826,2872,3402,126978,62139
13,서대문구,463268,619953,1854,1826,2872,3402,126978,62139
14,서초구,463268,619953,1854,1826,2872,3402,126978,62139
15,성동구,463268,619953,1854,1826,2872,3402,126978,62139
16,성북구,463268,619953,1854,1826,2872,3402,126978,62139
17,송파구,463268,619953,1854,1826,2872,3402,126978,62139
18,양천구,463268,619953,1854,1826,2872,3402,126978,62139
19,영등포구,463268,619953,1854,1826,2872,3402,126978,62139
20,용산구,463268,619953,1854,1826,2872,3402,126978,62139
21,은평구,463268,619953,1854,1826,2872,3402,126978,62139
22,종로구,463268,619953,1854,1826,2872,3402,126978,62139
23,중구,463268,619953,1854,1826,2872,3402,126978,62139
24,중랑구,463268,619953,1854,1826,2872,3402,126978,62139

## 문화예술종사자수

In [7]:
# 계산을 위한 Table
# 서울시 구별 데이터
data = {
    '구': ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구'],
}
# 데이터 프레임 생성
cal_df = pd.DataFrame(data)
cal_df

       구
0    강남구
1    강동구
2    강북구
3    강서구
4    관악구
5    광진구
6    구로구
7    금천구
8    노원구
9    도봉구
10  동대문구
11   동작구
12   마포구
13  서대문구
14   서초구
15   성동구
16   성북구
17   송파구
18   양천구
19  영등포구
20   용산구
21   은평구
22   종로구
23    중구
24   중랑구

In [12]:
# (ContentsCreator_2022/ContentsCreator_2021)*100
cal_df['ContentsCreator'] = art_manpower_index['ContentsCreator_2022']/art_manpower_index['ContentsCreator_2021']
cal_df['ContentsCreator'] = cal_df['ContentsCreator']*100
cal_df

       구  ContentsCreator
0    강남구       133.821676
1    강동구       133.821676
2    강북구       133.821676
3    강서구       133.821676
4    관악구       133.821676
5    광진구       133.821676
6    구로구       133.821676
7    금천구       133.821676
8    노원구       133.821676
9    도봉구       133.821676
10  동대문구       133.821676
11   동작구       133.821676
12   마포구       133.821676
13  서대문구       133.821676
14   서초구       133.821676
15   성동구       133.821676
16   성북구       133.821676
17   송파구       133.821676
18   양천구       133.821676
19  영등포구       133.821676
20   용산구       133.821676
21   은평구       133.821676
22   종로구       133.821676
23    중구       133.821676
24   중랑구       133.821676

In [13]:
final_art_manpower_index['Number_of_cultural_workers'] = cal_df['ContentsCreator']
final_art_manpower_index

       구  Number_of_cultural_workers
0    강남구                  133.821676
1    강동구                  133.821676
2    강북구                  133.821676
3    강서구                  133.821676
4    관악구                  133.821676
5    광진구                  133.821676
6    구로구                  133.821676
7    금천구                  133.821676
8    노원구                  133.821676
9    도봉구                  133.821676
10  동대문구                  133.821676
11   동작구                  133.821676
12   마포구                  133.821676
13  서대문구                  133.821676
14   서초구                  133.821676
15   성동구                  133.821676
16   성북구                  133.821676
17   송파구                  133.821676
18   양천구                  133.821676
19  영등포구                  133.821676
20   용산구                  133.821676
21   은평구                  133.821676
22   종로구                  133.821676
23    중구                  133.821676
24   중랑구                  133.821676

## 문화예술활동가수

In [14]:
# 계산을 위한 Table
# 서울시 구별 데이터
data = {
    '구': ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구'],
}
# 데이터 프레임 생성
cal_df = pd.DataFrame(data)
cal_df

       구
0    강남구
1    강동구
2    강북구
3    강서구
4    관악구
5    광진구
6    구로구
7    금천구
8    노원구
9    도봉구
10  동대문구
11   동작구
12   마포구
13  서대문구
14   서초구
15   성동구
16   성북구
17   송파구
18   양천구
19  영등포구
20   용산구
21   은평구
22   종로구
23    중구
24   중랑구

In [18]:
# ((performanceTeam_2021 / performanceTeam_2021), (applicants_2023/applicants_2022))*100
cal_df['performanceTeam'] = art_manpower_index['performanceTeam_2021']/art_manpower_index['performanceTeam_2021']
cal_df['performanceTeam'] = cal_df['performanceTeam']*100
cal_df['applicants'] = art_manpower_index['applicants_2023']/art_manpower_index['applicants_2022']
cal_df['applicants'] = cal_df['applicants']*100
cal_df

       구  performanceTeam  applicants
0    강남구            100.0  118.454039
1    강동구            100.0  118.454039
2    강북구            100.0  118.454039
3    강서구            100.0  118.454039
4    관악구            100.0  118.454039
5    광진구            100.0  118.454039
6    구로구            100.0  118.454039
7    금천구            100.0  118.454039
8    노원구            100.0  118.454039
9    도봉구            100.0  118.454039
10  동대문구            100.0  118.454039
11   동작구            100.0  118.454039
12   마포구            100.0  118.454039
13  서대문구            100.0  118.454039
14   서초구            100.0  118.454039
15   성동구            100.0  118.454039
16   성북구            100.0  118.454039
17   송파구            100.0  118.454039
18   양천구            100.0  118.454039
19  영등포구            100.0  118.454039
20   용산구            100.0  118.454039
21   은평구            100.0  118.454039
22   종로구            100.0  118.454039
23    중구            100.0  118.454039
24   중랑구            100.0  118.454039

In [20]:
cal_df['performanceTeam_applicants'] = (cal_df['performanceTeam'] + cal_df['applicants'])/2
cal_df

       구  performanceTeam  applicants  performanceTeam_applicants
0    강남구            100.0  118.454039                  109.227019
1    강동구            100.0  118.454039                  109.227019
2    강북구            100.0  118.454039                  109.227019
3    강서구            100.0  118.454039                  109.227019
4    관악구            100.0  118.454039                  109.227019
5    광진구            100.0  118.454039                  109.227019
6    구로구            100.0  118.454039                  109.227019
7    금천구            100.0  118.454039                  109.227019
8    노원구            100.0  118.454039                  109.227019
9    도봉구            100.0  118.454039                  109.227019
10  동대문구            100.0  118.454039                  109.227019
11   동작구            100.0  118.454039                  109.227019
12   마포구            100.0  118.454039                  109.227019
13  서대문구            100.0  118.454039                  109.227019
14   서초구            100.0  118.454039                  109.227019
15   성동구            100.0  118.454039                  109.227019
16   성북구            100.0  118.454039                  109.227019
17   송파구            100.0  118.454039                  109.227019
18   양천구            100.0  118.454039                  109.227019
19  영등포구            100.0  118.454039                  109.227019
20   용산구            100.0  118.454039                  109.227019
21   은평구            100.0  118.454039                  109.227019
22   종로구            100.0  118.454039                  109.227019
23    중구            100.0  118.454039                  109.227019
24   중랑구            100.0  118.454039                  109.227019

In [21]:
final_art_manpower_index['Arts_and_Culture_Activist'] = cal_df['performanceTeam_applicants']
final_art_manpower_index

       구  Number_of_cultural_workers  Arts_and_Culture_Activist
0    강남구                  133.821676                 109.227019
1    강동구                  133.821676                 109.227019
2    강북구                  133.821676                 109.227019
3    강서구                  133.821676                 109.227019
4    관악구                  133.821676                 109.227019
5    광진구                  133.821676                 109.227019
6    구로구                  133.821676                 109.227019
7    금천구                  133.821676                 109.227019
8    노원구                  133.821676                 109.227019
9    도봉구                  133.821676                 109.227019
10  동대문구                  133.821676                 109.227019
11   동작구                  133.821676                 109.227019
12   마포구                  133.821676                 109.227019
13  서대문구                  133.821676                 109.227019
14   서초구                  133.821676                 109.227019
15   성동구                  133.821676                 109.227019
16   성북구                  133.821676                 109.227019
17   송파구                  133.821676                 109.227019
18   양천구                  133.821676                 109.227019
19  영등포구                  133.821676                 109.227019
20   용산구                  133.821676                 109.227019
21   은평구                  133.821676                 109.227019
22   종로구                  133.821676                 109.227019
23    중구                  133.821676                 109.227019
24   중랑구                  133.821676                 109.227019

## 문화예술콘텐츠건수

In [26]:
# 계산을 위한 Table
# 서울시 구별 데이터
data = {
    '구': ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구'],
}
# 데이터 프레임 생성
cal_df = pd.DataFrame(data)
cal_df

       구
0    강남구
1    강동구
2    강북구
3    강서구
4    관악구
5    광진구
6    구로구
7    금천구
8    노원구
9    도봉구
10  동대문구
11   동작구
12   마포구
13  서대문구
14   서초구
15   성동구
16   성북구
17   송파구
18   양천구
19  영등포구
20   용산구
21   은평구
22   종로구
23    중구
24   중랑구

In [27]:
# (Content_2020/Content_2020)*100
cal_df['Content'] = art_manpower_index['Content_2020']/art_manpower_index['Content_2020']
cal_df['Content'] = cal_df['Content']*100
cal_df

       구  Content
0    강남구    100.0
1    강동구    100.0
2    강북구    100.0
3    강서구    100.0
4    관악구    100.0
5    광진구    100.0
6    구로구    100.0
7    금천구    100.0
8    노원구    100.0
9    도봉구    100.0
10  동대문구    100.0
11   동작구    100.0
12   마포구    100.0
13  서대문구    100.0
14   서초구    100.0
15   성동구    100.0
16   성북구    100.0
17   송파구    100.0
18   양천구    100.0
19  영등포구    100.0
20   용산구    100.0
21   은평구    100.0
22   종로구    100.0
23    중구    100.0
24   중랑구    100.0

In [28]:
final_art_manpower_index['Number_of_cultural_contents'] = cal_df['Content']
final_art_manpower_index

,구,Number_of_cultural_workers,Arts_and_Culture_Activist,Number_of_cultural_contents
0,강남구,133.821676,109.227019,100.0
1,강동구,133.821676,109.227019,100.0
2,강북구,133.821676,109.227019,100.0
3,강서구,133.821676,109.227019,100.0
4,관악구,133.821676,109.227019,100.0
5,광진구,133.821676,109.227019,100.0
6,구로구,133.821676,109.227019,100.0
7,금천구,133.821676,109.227019,100.0
8,노원구,133.821676,109.227019,100.0
9,도봉구,133.821676,109.227019,100.0
10,동대문구,133.821676,109.227019,100.0
11,동작구,133.821676,109.227019,100.0
12,마포구,133.821676,109.227019,100.0
13,서대문구,133.821676,109.227019,100.0
14,서초구,133.821676,109.227019,100.0
15,성동구,133.821676,109.227019,100.0
16,성북구,133.821676,109.227019,100.0
17,송파구,133.821676,109.227019,100.0
18,양천구,133.821676,109.227019,100.0
19,영등포구,133.821676,109.227019,100.0
20,용산구,133.821676,109.227019,100.0
21,은평구,133.821676,109.227019,100.0
22,종로구,133.821676,109.227019,100.0
23,중구,133.821676,109.227019,100.0
24,중랑구,133.821676,109.227019,100.0

## 인력지수

In [34]:
# 계산을 위한 Table
# 서울시 구별 데이터
data = {
    '구': ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구'],
}
# 데이터 프레임 생성
cal_df = pd.DataFrame(data)
cal_df

       구
0    강남구
1    강동구
2    강북구
3    강서구
4    관악구
5    광진구
6    구로구
7    금천구
8    노원구
9    도봉구
10  동대문구
11   동작구
12   마포구
13  서대문구
14   서초구
15   성동구
16   성북구
17   송파구
18   양천구
19  영등포구
20   용산구
21   은평구
22   종로구
23    중구
24   중랑구

In [35]:
cal_df['Workforce_Index'] = final_art_manpower_index['Number_of_cultural_workers'] + final_art_manpower_index['Arts_and_Culture_Activist']
cal_df['Workforce_Index'] = cal_df['Workforce_Index']/2
cal_df

       구  Workforce_Index
0    강남구       121.524348
1    강동구       121.524348
2    강북구       121.524348
3    강서구       121.524348
4    관악구       121.524348
5    광진구       121.524348
6    구로구       121.524348
7    금천구       121.524348
8    노원구       121.524348
9    도봉구       121.524348
10  동대문구       121.524348
11   동작구       121.524348
12   마포구       121.524348
13  서대문구       121.524348
14   서초구       121.524348
15   성동구       121.524348
16   성북구       121.524348
17   송파구       121.524348
18   양천구       121.524348
19  영등포구       121.524348
20   용산구       121.524348
21   은평구       121.524348
22   종로구       121.524348
23    중구       121.524348
24   중랑구       121.524348

In [36]:
final_art_manpower_index['Workforce_Index'] = cal_df['Workforce_Index']
final_art_manpower_index

,구,Number_of_cultural_workers,Arts_and_Culture_Activist,Number_of_cultural_contents,Workforce_Index
0,강남구,133.821676,109.227019,100.0,121.524348
1,강동구,133.821676,109.227019,100.0,121.524348
2,강북구,133.821676,109.227019,100.0,121.524348
3,강서구,133.821676,109.227019,100.0,121.524348
4,관악구,133.821676,109.227019,100.0,121.524348
5,광진구,133.821676,109.227019,100.0,121.524348
6,구로구,133.821676,109.227019,100.0,121.524348
7,금천구,133.821676,109.227019,100.0,121.524348
8,노원구,133.821676,109.227019,100.0,121.524348
9,도봉구,133.821676,109.227019,100.0,121.524348
10,동대문구,133.821676,109.227019,100.0,121.524348
11,동작구,133.821676,109.227019,100.0,121.524348
12,마포구,133.821676,109.227019,100.0,121.524348
13,서대문구,133.821676,109.227019,100.0,121.524348
14,서초구,133.821676,109.227019,100.0,121.524348
15,성동구,133.821676,109.227019,100.0,121.524348
16,성북구,133.821676,109.227019,100.0,121.524348
17,송파구,133.821676,109.227019,100.0,121.524348
18,양천구,133.821676,109.227019,100.0,121.524348
19,영등포구,133.821676,109.227019,100.0,121.524348
20,용산구,133.821676,109.227019,100.0,121.524348
21,은평구,133.821676,109.227019,100.0,121.524348
22,종로구,133.821676,109.227019,100.0,121.524348
23,중구,133.821676,109.227019,100.0,121.524348
24,중랑구,133.821676,109.227019,100.0,121.524348

## 콘텐츠지수

In [37]:
# 계산을 위한 Table
# 서울시 구별 데이터
data = {
    '구': ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구'],
}
# 데이터 프레임 생성
cal_df = pd.DataFrame(data)
cal_df

       구
0    강남구
1    강동구
2    강북구
3    강서구
4    관악구
5    광진구
6    구로구
7    금천구
8    노원구
9    도봉구
10  동대문구
11   동작구
12   마포구
13  서대문구
14   서초구
15   성동구
16   성북구
17   송파구
18   양천구
19  영등포구
20   용산구
21   은평구
22   종로구
23    중구
24   중랑구

In [38]:
cal_df['Content_Index'] = final_art_manpower_index['Number_of_cultural_contents']
cal_df['Content_Index'] = cal_df['Content_Index']
cal_df

       구  Content_Index
0    강남구          100.0
1    강동구          100.0
2    강북구          100.0
3    강서구          100.0
4    관악구          100.0
5    광진구          100.0
6    구로구          100.0
7    금천구          100.0
8    노원구          100.0
9    도봉구          100.0
10  동대문구          100.0
11   동작구          100.0
12   마포구          100.0
13  서대문구          100.0
14   서초구          100.0
15   성동구          100.0
16   성북구          100.0
17   송파구          100.0
18   양천구          100.0
19  영등포구          100.0
20   용산구          100.0
21   은평구          100.0
22   종로구          100.0
23    중구          100.0
24   중랑구          100.0

In [39]:
final_art_manpower_index['Content_Index'] = cal_df['Content_Index']
final_art_manpower_index

,구,Number_of_cultural_workers,Arts_and_Culture_Activist,Number_of_cultural_contents,Workforce_Index,Content_Index
0,강남구,133.821676,109.227019,100.0,121.524348,100.0
1,강동구,133.821676,109.227019,100.0,121.524348,100.0
2,강북구,133.821676,109.227019,100.0,121.524348,100.0
3,강서구,133.821676,109.227019,100.0,121.524348,100.0
4,관악구,133.821676,109.227019,100.0,121.524348,100.0
5,광진구,133.821676,109.227019,100.0,121.524348,100.0
6,구로구,133.821676,109.227019,100.0,121.524348,100.0
7,금천구,133.821676,109.227019,100.0,121.524348,100.0
8,노원구,133.821676,109.227019,100.0,121.524348,100.0
9,도봉구,133.821676,109.227019,100.0,121.524348,100.0
10,동대문구,133.821676,109.227019,100.0,121.524348,100.0
11,동작구,133.821676,109.227019,100.0,121.524348,100.0
12,마포구,133.821676,109.227019,100.0,121.524348,100.0
13,서대문구,133.821676,109.227019,100.0,121.524348,100.0
14,서초구,133.821676,109.227019,100.0,121.524348,100.0
15,성동구,133.821676,109.227019,100.0,121.524348,100.0
16,성북구,133.821676,109.227019,100.0,121.524348,100.0
17,송파구,133.821676,109.227019,100.0,121.524348,100.0
18,양천구,133.821676,109.227019,100.0,121.524348,100.0
19,영등포구,133.821676,109.227019,100.0,121.524348,100.0
20,용산구,133.821676,109.227019,100.0,121.524348,100.0
21,은평구,133.821676,109.227019,100.0,121.524348,100.0
22,종로구,133.821676,109.227019,100.0,121.524348,100.0
23,중구,133.821676,109.227019,100.0,121.524348,100.0
24,중랑구,133.821676,109.227019,100.0,121.524348,100.0

## 예술창작/생산지수

In [42]:
final_art_manpower_index['art_manpower_index'] = final_art_manpower_index['Workforce_Index'] + final_art_manpower_index['Content_Index']
final_art_manpower_index['art_manpower_index'] = final_art_manpower_index['art_manpower_index']/2

In [43]:
final_art_manpower_index

,구,Number_of_cultural_workers,Arts_and_Culture_Activist,Number_of_cultural_contents,Workforce_Index,Content_Index,art_manpower_index
0,강남구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
1,강동구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
2,강북구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
3,강서구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
4,관악구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
5,광진구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
6,구로구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
7,금천구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
8,노원구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
9,도봉구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
10,동대문구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
11,동작구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
12,마포구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
13,서대문구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
14,서초구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
15,성동구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
16,성북구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
17,송파구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
18,양천구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
19,영등포구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
20,용산구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
21,은평구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
22,종로구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
23,중구,133.821676,109.227019,100.0,121.524348,100.0,110.762174
24,중랑구,133.821676,109.227019,100.0,121.524348,100.0,110.762174

In [44]:
final_art_manpower_index.to_csv('art_manpower_index.csv', encoding='utf-8-sig', index=False)